# @TODO figure out how database will work here
sudo: false
language: python
python:
  - "3.6"
services: mysql
install:
    - cd backend
    - pip install flake8==3.2.0
    - pip install -r requirements.txt

script:
    - python manage.py test
