version: '2'
services:
  backend:
      build:
        context: ./backend
      ports:
        - 8000:8000
      environment:
        - DJANGO_SETTINGS_MODULE=backend.settings
  webfrontend:
     build:
       context: ./webfrontend
     volumes:
       - ./:/usr/src/app
     command: npm start
     ports:
       - 4200:4200
  mobileapp:
     build:
       context: ./mobileapp
     ports:
       - 8100:8100
